services:
  # esm.dev:
  #   build:
  #     context: .
  #   depends_on: [esm, npm]
  #   environment:
  #     - NPM_REGISTRY=http://npm:4873
  #     - ESM_ORIGIN=http://esm:8080
  #     - ESM_STORAGE_PATH=/esmd
  #     - PORT=3000
  #   command:
  #     - start
  #     - /watch/*
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - ./docker-storage/esm/esmd:/esmd
  #     - ./test/packages:/watch:ro
  #   develop:
  #     watch:
  #       - action: sync+restart
  #         path: ./src
  #         target: /app/src
  #       - action: rebuild
  #         path: ./package.json
  #         target: /app/package.json
  esm:
    image: ghcr.io/esm-dev/esm.sh:latest
    environment:
      - NPM_TOKEN=fake
      - NPM_REGISTRY=http://npm:4873
      - LOG_LEVEL=debug
    ports:
      - '8080:8080'
    volumes:
      - ./docker-storage/esm/esmd:/esmd
  npm:
    image: verdaccio/verdaccio:latest
    ports:
      - '4873:4873'
