services:
  esm:
    image: ghcr.io/esm-dev/esm.sh:latest
    environment:
      - NPM_TOKEN=fake
      - NPM_REGISTRY=http://npm:4873
      - LOG_LEVEL=debug
    ports:
      - '8080:8080'
    volumes:
      - ./docker-storage/esm/npm:/esmd/npm
      - ./docker-storage/esm/storage:/esmd/storage
  npm:
    image: verdaccio/verdaccio:latest
    ports:
      - '4873:4873'
