#!/usr/bin/env sh
node --experimental-strip-types --no-warnings=ExperimentalWarning src/cli.ts wait-for-registry && \
node --experimental-strip-types --no-warnings=ExperimentalWarning src/cli.ts login && \
node --experimental-strip-types --no-warnings=ExperimentalWarning src/cli.ts $@
