name: Docker

on:
  workflow_call:
    inputs:
      version:
        description: The version to build and push
        required: true
        type: string

  workflow_dispatch:
    inputs:
      version:
        description: The version to build and push
        required: true
        type: string

jobs:
  push-image:
    uses: johngeorgewright/workflows/.github/workflows/push-image.yml@main
    permissions:
      contents: read
      packages: write
    with:
      image-name: ghcr.io/johngeorgewright/esm.dev
      image-tag: ${{ inputs.version }}
      registry: ghcr.io
    secrets:
      DOCKER_REPO_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_REPO_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
