name: Pull Request

on:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      esm:
        image: ghcr.io/esm-dev/esm.sh:latest
        env:
          NPM_TOKEN: fake
          NPM_REGISTRY: http://npm:4873
          LOG_LEVEL: debug
        ports:
          - '8080:8080'
        volumes:
          - ${{ github.workspace }}/esmd:/esmd

      npm:
        image: verdaccio/verdaccio:latest
        ports:
          - '4873:4873'

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Use Bun
        uses: oven-sh/setup-bun@v2

      - name: Install inotify
        run: |
          sudo apt-get update
          sudo apt-get install -y inotify-tools

      - name: Install
        run: bun install

      - name: Test Compilation
        run: bunx tsc

      - name: Test
        run: bun test
        env:
          ESM_STORAGE_PATH: ${{ github.workspace }}/esmd
