name: Pull Request

on:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Use Bun
        uses: oven-sh/setup-bun@v2

      - name: Install
        run: bun install

      - name: Test Compilation
        run: bunx tsc

      - uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          up-flags: --build
          down-flags: --volumes

      - name: Test
        run: | # shell
          sleep 5
          bun test
