name: Pull Request

on:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Use Bun
        uses: oven-sh/setup-bun@v2

      - name: Install
        run: bun install

      - name: Test Compilation
        run: tsc

      - uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: ./docker-compose.yml
          up-flags: --build

      - name: Test
        run: bun test

  compose-test:
    name: Compose Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Use Bun
        uses: oven-sh/setup-bun@v2

      - uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: ./test.yaml

      - run: curl 'http://0.0.0.0:8080'
