name: Publish

on:
  push:
    branches: [master]

concurrency:
  group: release

jobs:
  test:
    uses: ./.github/workflows/test.yml

  release:
    name: Release
    needs: [test]
    runs-on: ubuntu-latest
    outputs:
      new_release_published: ${{ steps.release.outputs.new_release_published }}
      version: ${{ steps.release.outputs.new_release_version }}
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout project
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - uses: actions/create-github-app-token@v3
        id: auth
        with:
          client-id: ${{ secrets.APP_CLIENT_ID }}
          private-key: ${{ secrets.APP_PEM }}
          permission-contents: write
          permission-issues: write
          permission-pull-requests: write

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v6
        id: release
        env:
          GITHUB_TOKEN: ${{ steps.auth.outputs.token }}
          NPM_CONFIG_PROVENANCE: true
        with:
          extra_plugins: |
            @semantic-release/git

  push-image:
    needs: [release]
    if: needs.release.outputs.new_release_published == 'true'
    permissions:
      packages: write
    uses: ./.github/workflows/docker.yml
    with:
      version: ${{ needs.release.outputs.version }}
