name: Test

on:
  pull_request:
  workflow_call:

concurrency:
  cancel-in-progress: true
  group: ${{ github.ref }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      esm:
        image: ghcr.io/esm-dev/esm.sh:latest
        env:
          NPM_TOKEN: fake
          NPM_REGISTRY: http://npm:4873
          LOG_LEVEL: debug
        options: --user root
        ports:
          - '8080:8080'
        volumes:
          - /home/runner/docker-storage/esmd/npm:/esmd/npm
          - /home/runner/docker-storage/esmd/storage:/esmd/storage

      npm:
        image: verdaccio/verdaccio:latest
        ports:
          - '4873:4873'

    container:
      image: denoland/deno:alpine
      env:
        ESM_ORIGIN: http://esm:8080
        ESM_STORAGE_PATH: /esmd
        REGISTRY: http://npm:4873
      options: --user root
      volumes:
        - /home/runner/docker-storage/esmd:/esmd

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Install Bash
        run: apk update && apk add bash

      - name: Install
        run: deno install

      - name: Lint
        run: deno lint

      - name: Test Compilation
        run: deno check

      - name: Test
        run: deno task test

      - name: Test NPM Build
        run: deno task npm --test
