name: Test

on:
  pull_request:
  workflow_call:

concurrency:
  cancel-in-progress: true
  group: ${{ github.ref }}

jobs:
  test-deno:
    name: Test Deno
    runs-on: ubuntu-latest

    services:
      esm:
        image: ghcr.io/esm-dev/esm.sh:latest
        env:
          NPM_TOKEN: fake
          NPM_REGISTRY: http://npm:4873
          LOG_LEVEL: debug
        options: --user root
        ports:
          - '8080:8080'
        volumes:
          - /home/runner/docker-storage/esmd/npm:/esmd/npm
          - /home/runner/docker-storage/esmd/storage:/esmd/storage

      npm:
        image: verdaccio/verdaccio:latest
        ports:
          - '4873:4873'

    env:
      ESM_ORIGIN: http://localhost:8080
      ESM_STORAGE_PATH: /home/runner/docker-storage/esmd
      REGISTRY: http://localhost:4873 

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install
        run: deno install

      - name: Lint
        run: deno lint

      - name: Test Compilation
        run: deno check

      - name: Test
        run: deno task test

  test-node:
    name: Test Node
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22, 24]

    services:
      esm:
        image: ghcr.io/esm-dev/esm.sh:latest
        env:
          NPM_TOKEN: fake
          NPM_REGISTRY: http://npm:4873
          LOG_LEVEL: debug
        options: --user root
        ports:
          - '8080:8080'
        volumes:
          - /home/runner/docker-storage/esmd/npm:/esmd/npm
          - /home/runner/docker-storage/esmd/storage:/esmd/storage

      npm:
        image: verdaccio/verdaccio:latest
        ports:
          - '4873:4873'

    env:
      ESM_ORIGIN: http://localhost:8080
      ESM_STORAGE_PATH: /home/runner/docker-storage/esmd
      REGISTRY: http://localhost:4873 

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Test NPM Build
        run: deno task npm --test
